SELECT
    CASE WHEN CL.TINGRESOS < 13000 THEN 'Bajo'
         WHEN CL.TINGRESOS BETWEEN 13000 AND 30000 THEN 'Medio'
         ELSE 'Alto'
    END AS NIVEL_INGRESO,
    COUNT(DISTINCT C.ID_CONTRATO) AS TOTAL_CONTRATOS,
    SUM(CASE WHEN C.IMPAGO = 1 THEN 1 ELSE 0 END) AS CONTRATOS_IMPAGADOS,
    ROUND(100.0 * SUM(CASE WHEN C.IMPAGO = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS TASA_IMPAGO
FROM Contratos C
JOIN Solicitudes S ON C.ID_SOLICITUD = S.ID_SOLICITUD
JOIN Clientes CL ON S.ID_CLIENTE = CL.ID_CLIENTE
GROUP BY NIVEL_INGRESO
ORDER BY NIVEL_INGRESO;
