SELECT
    CASE
        WHEN C.EDAD < 25 THEN '18-24'
        WHEN C.EDAD BETWEEN 25 AND 34 THEN '25-34'
        WHEN C.EDAD BETWEEN 35 AND 44 THEN '35-44'
        WHEN C.EDAD BETWEEN 45 AND 54 THEN '45-54'
        WHEN C.EDAD BETWEEN 55 AND 64 THEN '55-64'
        ELSE '65+'
    END AS FRANJA_EDAD,
    COUNT(DISTINCT S.ID_CLIENTE) AS TOTAL_SOLICITUDES,
    SUM(CASE WHEN S.DECISION='ACEPTADO' THEN 1 ELSE 0 END) AS ACEPTADAS,
    ROUND(100.0 * SUM(CASE WHEN S.DECISION='ACEPTADO' THEN 1 ELSE 0 END) / COUNT(DISTINCT S.ID_CLIENTE), 2) AS TASA_ACEPTACION
FROM Solicitudes S
JOIN Clientes C ON S.ID_CLIENTE = C.ID_CLIENTE
GROUP BY FRANJA_EDAD
ORDER BY FRANJA_EDAD;
