SELECT 
    COUNT(DISTINCT S.ID_SOLICITUD) AS NUM_ACEPTADAS,
    COUNT(DISTINCT C.ID_CONTRATO) AS NUM_CONVERTIDAS_EN_CONTRATO,
    ROUND(100.0 * COUNT(DISTINCT C.ID_CONTRATO) / COUNT(DISTINCT S.ID_SOLICITUD), 2) AS PORCENTAJE_CONVERTIDAS
FROM Solicitudes S
LEFT JOIN Contratos C ON S.ID_SOLICITUD = C.ID_SOLICITUD
WHERE S.DECISION = 'ACEPTADO';
