SELECT
    MARCA_FRAUDE,
    COUNT(*) AS NUM_CLIENTES,
    AVG(EDAD) AS EDAD_MEDIA,
    AVG(TINGRESOS) AS INGRESO_MEDIO,
    AVG(GASTOSVIV + OTROSGASTOS1) AS GASTO_MEDIO
FROM Clientes
GROUP BY MARCA_FRAUDE;
