SELECT
    C.NACIONALIDAD,
    CASE
        WHEN C.EDAD < 30 THEN 'Menores de 30'
        WHEN C.EDAD BETWEEN 30 AND 50 THEN '30-50'
        ELSE '50+'
    END AS FRANJA_EDAD,
    COUNT(*) AS NUM_SOLICITUDES,
    round(AVG(S.IMPORTE_SOL)*1000,2) AS IMPORTE_MEDIO_SOLICITADO
FROM Clientes C
JOIN Solicitudes S ON C.ID_CLIENTE = S.ID_CLIENTE
GROUP BY C.NACIONALIDAD, FRANJA_EDAD
ORDER BY NUM_SOLICITUDES DESC;
