SELECT
    CASE
        WHEN EDAD < 25 THEN '18-24'
        WHEN EDAD BETWEEN 25 AND 34 THEN '25-34'
        WHEN EDAD BETWEEN 35 AND 44 THEN '35-44'
        WHEN EDAD BETWEEN 45 AND 54 THEN '45-54'
        WHEN EDAD BETWEEN 55 AND 64 THEN '55-64'
        ELSE '65+'
    END AS FRANJA_EDAD,
    COUNT(*) AS NUM_CLIENTES,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM Clientes), 2) AS PORCENTAJE
FROM Clientes
GROUP BY FRANJA_EDAD
ORDER BY FRANJA_EDAD;
