SELECT
    CASE
        WHEN (TINGRESOS - (GASTOSVIV + OTROSGASTOS1)) < 9000 THEN 'Bajo'
        WHEN (TINGRESOS - (GASTOSVIV + OTROSGASTOS1)) BETWEEN 9001 AND 22000 THEN 'Medio'
        ELSE 'Alto'
    END AS NIVEL_ADQUISITIVO,
    COUNT(*) AS NUM_CLIENTES,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM Clientes), 2) AS PORCENTAJE
FROM Clientes
GROUP BY NIVEL_ADQUISITIVO
ORDER BY NUM_CLIENTES DESC;
