SELECT 
    MOTIVO_RECHAZO,
    COUNT(*) AS NUM_RECHAZOS,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM Solicitudes WHERE DECISION='RECHAZADO'), 2) AS PORCENTAJE
FROM Solicitudes
WHERE DECISION = 'RECHAZADO'
GROUP BY MOTIVO_RECHAZO
ORDER BY NUM_RECHAZOS DESC;
