SELECT
    DATE(FECHA_DEMANDA) AS FECHA,
    COUNT(*) AS TOTAL_SOLICITUDES,
    SUM(CASE WHEN DECISION='ABANDONADO' THEN 1 ELSE 0 END) AS ABANDONADAS,
    ROUND(100.0 * SUM(CASE WHEN DECISION='ABANDONADO' THEN 1 ELSE 0 END) / COUNT(*), 2) AS TASA_ABANDONO
FROM Solicitudes
GROUP BY DATE(FECHA_DEMANDA)
ORDER BY FECHA;
