SELECT
    CASE
        WHEN CL.EDAD BETWEEN 18 AND 24 THEN '18-24'
        WHEN CL.EDAD BETWEEN 25 AND 34 THEN '25-34'
        WHEN CL.EDAD BETWEEN 35 AND 44 THEN '35-44'
        WHEN CL.EDAD BETWEEN 45 AND 54 THEN '45-54'
        WHEN CL.EDAD BETWEEN 55 AND 64 THEN '55-64'
        ELSE '65+'
    END AS FRANJA_EDAD,
    CASE
        WHEN (CL.TINGRESOS - (CL.GASTOSVIV + CL.OTROSGASTOS1)) < 5000 THEN 'Bajo'
        WHEN (CL.TINGRESOS - (CL.GASTOSVIV + CL.OTROSGASTOS1)) BETWEEN 5001 AND 10000 THEN 'Medio-Bajo'
        WHEN (CL.TINGRESOS - (CL.GASTOSVIV + CL.OTROSGASTOS1)) BETWEEN 10001 AND 15000 THEN 'Medio-Alto'
        ELSE 'Alto'
    END AS NIVEL_INGRESO_NETO,
    COUNT(DISTINCT C.ID_CONTRATO) AS TOTAL_CONTRATOS,
    SUM(CASE WHEN C.IMPAGO = 1 THEN 1 ELSE 0 END) AS IMPAGOS,
    ROUND(100.0 * SUM(CASE WHEN C.IMPAGO = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS TASA_IMPAGO
FROM Contratos C
JOIN Solicitudes S ON C.ID_SOLICITUD = S.ID_SOLICITUD
JOIN Clientes CL ON S.ID_CLIENTE = CL.ID_CLIENTE
GROUP BY FRANJA_EDAD, NIVEL_INGRESO_NETO
ORDER BY FRANJA_EDAD, NIVEL_INGRESO_NETO;

