SELECT
    COUNT(*) AS TOTAL_CONTRATOS,
    SUM(CASE WHEN IMPAGO = 1 THEN 1 ELSE 0 END) AS CONTRATOS_IMPAGADOS,
    ROUND(100.0 * SUM(CASE WHEN IMPAGO = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS TASA_IMPAGO
FROM Contratos;
